// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwnUurZBr-Kyj2-biGdh8e3V3oGqX2THE',
    appId: '1:109367698421:web:5fda4d2189dd31595b76bc',
    messagingSenderId: '109367698421',
    projectId: 'maps-app-3efb4',
    authDomain: 'maps-app-3efb4.firebaseapp.com',
    storageBucket: 'maps-app-3efb4.appspot.com',
    measurementId: 'G-3KRC0LTC74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCftejqJETzI2Z9CnGiZh4YOG68ipwoPg',
    appId: '1:109367698421:android:69c8b1c7296cf6405b76bc',
    messagingSenderId: '109367698421',
    projectId: 'maps-app-3efb4',
    storageBucket: 'maps-app-3efb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS898FEAgOjRI2Vbq218TtD_lDG_3L0nI',
    appId: '1:109367698421:ios:01c3a2f5b855aba35b76bc',
    messagingSenderId: '109367698421',
    projectId: 'maps-app-3efb4',
    storageBucket: 'maps-app-3efb4.appspot.com',
    iosBundleId: 'com.example.mapsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS898FEAgOjRI2Vbq218TtD_lDG_3L0nI',
    appId: '1:109367698421:ios:985f0c7c2f5e5a6e5b76bc',
    messagingSenderId: '109367698421',
    projectId: 'maps-app-3efb4',
    storageBucket: 'maps-app-3efb4.appspot.com',
    iosBundleId: 'com.example.mapsApp.RunnerTests',
  );
}
